"""create buddy_profiles

Revision ID: 126e74612131
Revises: 8657e396aedc
Create Date: 2026-05-11 15:18:42.318184

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '126e74612131'
down_revision: str | None = '8657e396aedc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buddy_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('looking_for', sa.String(length=500), nullable=False),
    sa.Column('courses', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('available_days', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('study_style', sa.String(length=20), nullable=False),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(contact_info->>'instagram') IS NOT NULL OR (contact_info->>'discord') IS NOT NULL OR (contact_info->>'telefon') IS NOT NULL", name='ck_buddy_profiles_contact_info_at_least_one'),
    sa.CheckConstraint("study_style IN ('quiet', 'group', 'cafe')", name='ck_buddy_profiles_study_style_valid'),
    sa.CheckConstraint('COALESCE(array_length(available_days, 1), 0) >= 1', name='ck_buddy_profiles_available_days_nonempty'),
    sa.CheckConstraint('COALESCE(array_length(courses, 1), 0) >= 1', name='ck_buddy_profiles_courses_nonempty'),
    sa.CheckConstraint('char_length(looking_for) >= 10', name='ck_buddy_profiles_looking_for_min_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_buddy_profiles_available_days_gin', 'buddy_profiles', ['available_days'], unique=False, postgresql_using='gin')
    op.create_index('ix_buddy_profiles_courses_gin', 'buddy_profiles', ['courses'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_buddy_profiles_study_style'), 'buddy_profiles', ['study_style'], unique=False)
    op.create_index(op.f('ix_buddy_profiles_updated_at'), 'buddy_profiles', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buddy_profiles_updated_at'), table_name='buddy_profiles')
    op.drop_index(op.f('ix_buddy_profiles_study_style'), table_name='buddy_profiles')
    op.drop_index('ix_buddy_profiles_courses_gin', table_name='buddy_profiles', postgresql_using='gin')
    op.drop_index('ix_buddy_profiles_available_days_gin', table_name='buddy_profiles', postgresql_using='gin')
    op.drop_table('buddy_profiles')
    # ### end Alembic commands ###
