"""create notes

Revision ID: a3b16a0fbcd8
Revises: c7138c15b1d1
Create Date: 2026-05-07 22:51:35.604003

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a3b16a0fbcd8'
down_revision: str | None = 'c7138c15b1d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_course_code'), 'notes', ['course_code'], unique=False)
    op.create_index('ix_notes_course_semester', 'notes', ['course_code', 'semester'], unique=False)
    op.create_index(op.f('ix_notes_semester'), 'notes', ['semester'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_semester'), table_name='notes')
    op.drop_index('ix_notes_course_semester', table_name='notes')
    op.drop_index(op.f('ix_notes_course_code'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
